@echo off
set SYSDRV=C:
cd %SYSDRV%\users\jtadmin\desktop\JH
%FMDUDIR%\pictview.exe 2Dequ1.jpg --l --nocls
%FMDUDIR%\pictview.exe 2Dequ2.jpg --l --nocls
%FMDUDIR%\pictview.exe 3Dfunc1.jpg --l --nocls
%FMDUDIR%\pictview.exe 3Dfunc2.jpg --l --nocls
%FMDUDIR%\pictview.exe 3Dfunc3.jpg --l --nocls
%FMDUDIR%\pictview.exe 2Dheart.jpg --l --nocls
%FMDUDIR%\pictview.exe 3Dheart.jpg --l --nocls
%FMDUDIR%\pictview.exe period1.jpg --l --nocls
%FMDUDIR%\pictview.exe period2.jpg --l --nocls
%FMDUDIR%\pictview.exe period3.jpg --l --nocls
%FMDUDIR%\pictview.exe period4.jpg --l --nocls
%FMDUDIR%\pictview.exe period5.jpg --l --nocls
%FMDUDIR%\pictview.exe YHT.PNG --l --nocls
%FMDUDIR%\pictview.exe CCTVlogo.PNG --l --nocls
%FMDUDIR%\pictview.exe 2Ddraft.PNG --l --nocls
%FMDUDIR%\pictview.exe 3Ddraft.PNG --l --nocls
%FMDUDIR%\pictview.exe lotus.jpg --l --nocls
%FMDUDIR%\pictview.exe Tix.PNG --l --nocls
%FMDUDIR%\pictview.exe czftzk1.PNG --l --nocls
%FMDUDIR%\pictview.exe czftzk2.PNG --l --nocls
%FMDUDIR%\pictview.exe czftzk3.PNG --l --nocls
%FMDUDIR%\pictview.exe czftzk4.PNG --l --nocls
%FMDUDIR%\pictview.exe 3dball.PNG --l --nocls
%FMDUDIR%\pictview.exe zfsin.jpg --l
cd %SYSDRV%\
